CREATE TABLE public.loan (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	loan_time varchar(255) NULL,
  CONSTRAINT loan_pkey PRIMARY KEY (id)
);

ALTER TABLE public.book ADD loan_id int8;
ALTER TABLE public.book ADD FOREIGN KEY (loan_id) REFERENCES loan(id);