CREATE TABLE public.book (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(255) NOT NULL,
	resume varchar(500) NOT NULL,
	isbn varchar(255) NOT NULL,
	author varchar(255) NOT NULL,
	year_book timestamp NULL,
  emprestimo_id int8 NULL,
  CONSTRAINT book_pkey PRIMARY KEY (id),
  CONSTRAINT fk57n8va7u85bkhvhulh5cn4g9r FOREIGN KEY (emprestimo_id) REFERENCES loan(id)
);

CREATE TABLE public.loan (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	loan_time varchar(255) NULL,
  CONSTRAINT loan_pkey PRIMARY KEY (id)
);